typing package missing
def params(song: Song) -> dict[str]:
TypeError: 'type' object is not subscriptable

def run(song: Song, params: dict[str, Any]):
NameError: name 'Any' is not defined